server:
  port: 9000

zuul:
  ignoredServices: '*'
  prefix: /
  routes:
    employees:
      path: /employee-service/**
      serviceId: EMPLOYEE-SERVICE
      strip-prefix: false
    results:
      path: /department-service/**
      serviceId: DEPARTMENT-SERVICE
      strip-prefix: false


endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
